name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
    name: build
    steps:
      - uses: actions/checkout@v4.2.1

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{matrix.java}}

      - name: Build with Maven
        run: mvn -B package --file pom.xml